# Generated by Django 5.2.2 on 2025-06-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fibre',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='calorie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
